### ISSUE TITLE
Stacked modal reopens on close

### ISSUE THREAD

**Issue by jagabs** [GreenFlag31/modal-library#1]
Hey man nice work! I just have one problem, when i stacked like 4-5 modals and close it fast, sometimes it reopens do you whats happening? been trying to debug it.

**Comment by GreenFlag31** [comment]
Hi Jagabs,

Thanks you for your message. I try to reproduce the issue. 

To close it fast, are you using the escape key or clicking outside (click on the overlay), or press on a button in the content of the modal that triggers the modalService to close? 
Are you using animations? 

Please make sure that:
- You are closing / opening different components. If you try to close and open the same component, it might create bugs.
- You are not applying an opening effect animation on a closing modal, giving the impression that it 'reappears'.
- If you press on a button inside the content of your modal to close it, make sure you call the close method and are not opening a new modal.

Meanwhile, I found a bug that cause the modal to not close when different animations were applied on multiple stacked modals. I've uploaded a new version on npm (v0.0.5).

Could you:
- install the latest version
- check the mentionned points on your side aswell
- give me a feedback?

The demo page has been updated aswel so you can check it out: https://greenflag31.github.io/modal-library/ngx-modal-ease 

Thank you

**Comment by jagabs** [comment]
hey working now as expected! 

It was reproducible with both esc and button modalService to close.
I was using different components for every modal. Yes my animations are different.
