### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by sertal70** [GreenFlag31/modal-library#3]
Hi, 
thank you for this useful library!

Currently it requires Angular 17, could be possibile to extend compatibility back to v16?

**Comment by GreenFlag31** [comment]
Hi. 

You can `npm i --force  ngx-modal-ease`, there is no code problems between these two versions in my library. I have just tested a V16 application, it correctly works.

**Comment by sertal70** [comment]
I did it, but my customer complains about using `--force`. One could update the project to v17, but there are other business priorities right now and we don't have time to spend on that. Any other chance?

**Comment by GreenFlag31** [comment]
Sure.

npm i the version 0.0.6 that I just pushed (current 0.0.7). For more info visit npm: https://www.npmjs.com/package/ngx-modal-ease?activeTab=readme

Provide me a feedback if you encounter any error.

**Comment by sertal70** [comment]
That's really great, thank you so much!
