### ISSUE TITLE
Emit close on actions

### ISSUE THREAD

**Issue by jerome-aluffi-perso** [GreenFlag31/modal-library#5]
Hi,

Is possible to send close event when the modal is closed by actions (click or escape) ?

Best regards

**Comment by GreenFlag31** [comment]
Hi.

I can think about it. Which version are you using ?

Cheers

**Comment by jerome-aluffi-perso** [comment]
"ngx-modal-ease": "^0.1.0"
For Angular V18.

**Comment by GreenFlag31** [comment]
Solved in v0.1.1.
