### ISSUE TITLE
Pass injector

### ISSUE THREAD

**Issue by jerome-aluffi-perso** [GreenFlag31/modal-library#6]
Hi,

Is possible to pass the parent injector in the options  ?
`
export class YComponent {
injector = inject(Injector);
modalService = inject(ModalService);
....
showModal() {

this.modalService.open(XXModalComponent, 
       {
             **injector: this.injector**
       }
);
}

}`

Best regards,

**Comment by GreenFlag31** [comment]
This injector will then be used in the injected component, right? Then you can pass it in the data option:
```javascript
this.modalService.open(XXModalComponent, {
...
data: {
     injector: this.injector
  }
}
```

**Comment by jerome-aluffi-perso** [comment]
Yes, the injector will be used in the injected component.

If i pass it in the data option so i can't use :
`myService = inject(MyService)`

Is it possible to have a property in the options to add the injector of the parent component so that it is transparent?

` this.newComponent = createComponent(componentToCreate, {
      environmentInjector: this.injector,
      **elementInjector : options.injector** /*is valid ?*/
    });`

**Comment by GreenFlag31** [comment]
Hi.
I have implemented the desired changes of the 2 opened tickets.

Could you:
1.  Uninstall the ngx-modal-ease in your application
2. Put following tarball file at the root of your application: [ngx-modal-ease-0.1.0.tgz](https://github.com/user-attachments/files/16039752/ngx-modal-ease-0.1.0.tgz)
3. `npm i ngx-modal-ease-0.1.0.tgz` in your project (extension should be included in the command)
4. Test the functionnalities
5. Provide me a feedback?

The response of a closing modal in now under the form:
```javascript
interface ModalResponse {
  closedOnClickOrEscape: boolean;
  data: unknown;
}
```

cheers

**Comment by jerome-aluffi-perso** [comment]
Hi,

npm i -S ngx-modal-ease-0.1.0.tgz doesn't seem to work.

npm warn tarball tarball data for file:ngx-modal-ease-0.1.0.tgz (null)
seems to be corrupted. Trying again.
npm warn tarball tarball data for file:ngx-modal-ease-0.1.0.tgz (null)
seems to be corrupted. Trying again.
npm error code ENOENT

Le sam. 29 juin 2024 à 12:59, Manu Claeys ***@***.***> a
écrit :

**Comment by GreenFlag31** [comment]
Hi

This problem usually occurs because the current ngx-modal-ease has not been uninstalled or uncorrectly uninstalled.

Could you make sure that: 

- You put the tarball at the root of your project
- You have uninstalled ngx-modal-ease
- Check if it's not present anymore in the node_modules. If still present, delete it manually
- Could you try without -S ? I don't know if this has any influence (npm i ngx-modal-ease-0.1.0.tgz)
- If it still does not work, I will look at it, but I have no time today unfortunatelly

Cheers

**Comment by GreenFlag31** [comment]
Everything works on my side doing the recommanded steps. Did you achieve to test it?

**Comment by jerome-aluffi-perso** [comment]
Hi,

   - You put the tarball at the root of your project -> npm i tarball ??
   - You have uninstalled ngx-modal-ease -> ok
   - Check if it's not present anymore in the node_modules. If still
   present, delete it manually -> ok
   - Could you try without -S ? I don't know if this has any influence (npm
   i ngx-modal-ease-0.1.0.tgz)-> ok
   - If it still does not work, I will look at it, but I have no time today
   unfortunatelly -> ko


Le mar. 2 juil. 2024 à 18:55, Manu Claeys ***@***.***> a
écrit :

**Comment by GreenFlag31** [comment]
Yep, just  npm i ngx-modal-ease-0.1.0.tgz.

Tell me if it still doesn't work, I will publish a new version.

**Comment by jerome-aluffi-perso** [comment]
Hi,
 It still doesn't work.
Sorry.


Le mer. 3 juil. 2024 à 18:24, Manu Claeys ***@***.***> a
écrit :

**Comment by GreenFlag31** [comment]
"version": "0.1.1" has been pushed on npm.

Cheers

**Comment by jerome-aluffi-perso** [comment]
Hi,

I'm receiving the event close now and closedOnClickOrEscape is present.

Last request: Is possible to pass injector in property instead data properties and update the following line :
`this.newComponent = createComponent(componentToCreate, { environmentInjector: this.injector })`
If options.injector is null so nothing to do else set up the injector via options.injector ?

**Comment by GreenFlag31** [comment]
Hi

I'm not certain to understand what you mean. You can provide your injector in the Options interface (which I did not update in the documentation, that's updated now with the new version I'm going to push). The only way to communicate with the service is through the options. 

```javascript
Options {
  modal?: {
    enter?: string;
    leave?: string;
    top?: string;
    left?: string;
  };
  overlay?: {
    enter?: string;
    leave?: string;
    backgroundColor?: string;
  };
  size?: {
    height?: string;
    maxHeight?: string;
    width?: string;
    maxWidth?: string;
    padding?: string;
  };
  actions?: {
    escape?: boolean;
    click?: boolean;
  };
  data?: {
    [key: string]: unknown;
  };
  injector?: Injector;
}
```
![image](https://github.com/user-attachments/assets/62001539-3f52-4a79-b64e-9931697384f1)

Please check with the current version you have if it's fitting your needs and I will update a new version with updated documentation & export of the ModalResponse interface.

**Comment by jerome-aluffi-perso** [comment]
Hi,

I have v0.1.1 version and there isn't the injector property and modal response isn't exposed.

There isn't v0.1.2 :
`npm view ngx-modal-ease versions
[
  '0.0.1', '0.0.2',
  '0.0.3', '0.0.4',
  '0.0.5', '0.0.6',
  '0.0.7', '0.0.8',
  '0.0.9', '0.1.0',
  '0.1.1'
]`

**Comment by GreenFlag31** [comment]
There is not yet the v0.1.2, that's what I've said: "I will update a new version with updated documentation & export of the ModalResponse interface." => this comes in v0.1.2.

There is the injector property in the v0.1.1:
![image](https://github.com/user-attachments/assets/4ea3e9c9-a418-4e87-8502-19d212fd87eb)

![image](https://github.com/user-attachments/assets/3a729a07-10f5-4c28-920e-7fe5b2776f47)

As I said, please check if it's fitting your need, and if it's ok, I will publish the next version.

**Comment by jerome-aluffi-perso** [comment]
Hi,

It's perfect! I have the injector property.

Could you also expose the Options interface ?

**Comment by GreenFlag31** [comment]
New version has been published.

Cheers
